name = "Measures"
uuid = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
authors = ["JuliaGraphics contributors"]
version = "0.3.2"

[compat]
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
